# Generated by Django 3.2.18 on 2022-09-11 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'kata',
            },
        ),
        migrations.CreateModel(
            name='Mkoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'mkoa',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('kawaida', 'kawaida'), ('vipaji', 'vipaji'), ('ufundi', 'ufundi')], max_length=30)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('mixture', 'mixture')], max_length=20)),
                ('kata_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kata')),
            ],
            options={
                'db_table': 'school',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=200)),
                ('candidate_number', models.CharField(max_length=200)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=20)),
                ('kiswahili', models.CharField(max_length=1)),
                ('english', models.CharField(max_length=1)),
                ('maarifa', models.CharField(max_length=1)),
                ('hisabati', models.CharField(max_length=1)),
                ('science', models.CharField(max_length=1)),
                ('average_grade', models.CharField(max_length=1)),
                ('average_marks', models.CharField(max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('year', models.CharField(max_length=4)),
                ('kata_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kata')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mkoa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mkoa')),
            ],
            options={
                'db_table': 'wilaya',
            },
        ),
        migrations.CreateModel(
            name='StudentSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.school')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
            options={
                'db_table': 'student_school',
            },
        ),
        migrations.CreateModel(
            name='QuantityRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('year', models.CharField(max_length=4)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.school')),
            ],
            options={
                'db_table': 'quantity',
            },
        ),
        migrations.AddField(
            model_name='kata',
            name='wilaya_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.wilaya'),
        ),
    ]
