# Generated by Django 3.2.18 on 2022-09-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220911_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='type',
            field=models.CharField(choices=[('ward', 'ward'), ('special', 'special'), ('technical', 'technical')], max_length=30),
        ),
    ]
