# Generated by Django 3.2.18 on 2023-03-28 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230325_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='kata_id',
        ),
        migrations.AddField(
            model_name='student',
            name='wilaya_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.wilaya'),
            preserve_default=False,
        ),
    ]
